---
ldap_client_packages:
  - libnss-ldap
  - libpam-ldap
  - ldap-utils
  - nslcd
  - nscd

ldap_server_uri: ldap://ldap.example.com
ldap_base_dn: dc=example,dc=com
ldap_bind_dn: cn=admin,dc=example,dc=com
ldap_bind_password: ""
